- name: Include distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_os_family|lower }}.yml"
  tags:
   - dnsmasq

- include: dnsmasq.yml
- include: consul.yml
